# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
